#端口以及主目录路径   
server:
   port : 80
   servlet: 
      context-path : /
#配置ssl请将 server.port 配置 为 443，然后配置以下参数
#   http:
#      port : 80       
#   ssl:
#      key-store: webapp/ssl_www.svein.com.cn.pfx
#      key-store-password: xipYs081
#      keyStoreType: PKCS12
spring:
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#日志输出
logging:
   file:
      name: log/pv.log
   level: 
      root: info
      org.springframework: info
      qinyoyo: info
photo:
   password: 123456
#   no-video-thumb: true
   support-orientation: HeyTapBrowser,Firefox,Mac OS X,HuaweiBrowser,UCBrowser/13
#   root-path: E:\Photo\Archived
   root-path: I:\VVV\Archived\Video\210630
   ffmpeg: E:\Photo\ffmpeg.exe
   exiftool: E:\Photo\exiftool.exe