#端口以及主目录路径   
server:
   port : 80
   servlet: 
      context-path : /
#配置ssl请将 server.port 配置 为 443，然后配置以下参数
#   http:
#      port : 80       
#   ssl:
#      key-store: webapp/ssl_www.svein.com.cn.pfx
#      key-store-password: xipYs081
#      keyStoreType: PKCS12
spring:
# 正式环境设为false
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#日志输出
logging:
   file:
      name: log/pv.log
   level: 
      root: info
      org.springframework: info
      qinyoyo: debug
photo:
#   debug: true
   password: 8705087
   loop-timer: 2000
#   no-video-thumb: true
   html-editable: true
   support-orientation: HeyTapBrowser,Firefox,Mac OS X,HuaweiBrowser,UCBrowser/13
   root-path: G:\Photo\Archived
   ffmpeg: G:\Photo\ffmpeg.exe
   exiftool: G:\Photo\exiftool.exe