spring:
   jackson:
      time-zone: GMT+8
   mvc:
      static-path-pattern: /static/**

   freemarker:
      request-context-attribute: req  #req访问request
      suffix: .ftl  #后缀名
      content-type: text/html
      enabled: true
      cache: false #缓存配置
      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
      charset: UTF-8 #编码格式

server: 
   tomcat:
      uri-encoding: UTF-8   
management:
   endpoints:
       web: 
          exposure:         
            include: '*'
   endpoint: 
      health: 
         show-details: always
      shutdown: 
         enabled: false    
